### ISSUE TITLE
missing `data/D` data file?

### ISSUE THREAD

**Issue by inorton** [remainvoter/eu2019model#6]
I get a file-not-found error:

```
C:\Python36\python.exe -m eu2019model.recommend
Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\inb\PycharmProjects\eu2019model\eu2019model\recommend.py", line 56, in <module>
    sys.exit(main(args))
  File "C:\Users\inb\PycharmProjects\eu2019model\eu2019model\recommend.py", line 22, in main
    for region in engine.getAllRegions():
  File "C:\Users\inb\PycharmProjects\eu2019model\eu2019model\models.py", line 195, in getAllRegions
    return self.dbh.getAllRegions()
  File "C:\Users\inb\PycharmProjects\eu2019model\eu2019model\utilities.py", line 79, in getAllRegions
    with open(self.pathD) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/D'
```

**Comment by inorton** [comment]
Aha! I need to supply `--update`

**Comment by DrNickMartin** [comment]
Thanks, updated the documentation on the ReadMe
